### ISSUE TITLE
Why use the byte[] but not use the byte in ValidatingTextBox.Update

### ISSUE THREAD

**Issue by lindexi** [jamesmcroft/WinUX-UWP-Toolkit#1]
I have a problem that why use the ` byte[] isInvalid` in ValidatingTextBox.cs rather than use the byte?

I see the code use `isInvalid[0]` but not use other.That is the reason that I suggest use the byte rather that byte[] to ` isInvalid`.

Happy New Year to you.

**Comment by jamesmcroft** [comment]
I believe this is based on an early version of the control and was never changed to reflect the up-to-date functionality. Thanks for spotting this.

**Comment by jamesmcroft** [comment]
Resolved in commit [9d7528d](https://github.com/jamesmcroft/WinUX-UWP-Toolkit/commit/9d7528da267177b7e85e0c10d62fb69775b3f2ca)
