### ISSUE TITLE
ValidatingTextBox default state should not be "invalid"

### ISSUE THREAD

**Issue by igorkulman** [jamesmcroft/WinUX-UWP-Toolkit#12]
If I add a `ValidatingTextBox` with some rules to a page it shows as "invalid" even before the user starts typing or focuses it.

**Comment by jamesmcroft** [comment]
I'll explore this. Have you set the mandatory property to true?

**Comment by igorkulman** [comment]
Yes, `IsMandatory="True"` and two way binding for `Text`

**Comment by jamesmcroft** [comment]
By setting the mandatory flag, the control will default to invalid if there is no text. This is intended.

**Comment by jamesmcroft** [comment]
I'm going to close this off. If we believe this is still an issue, please let me know :smile:
