### ISSUE TITLE
Can't get rid of warnings

### ISSUE THREAD

**Issue by jsrijkee** [jamesmcroft/WinUX-UWP-Toolkit#14]
Hi,

I'm completely new with WinUX.UWP.
Installed all the packages from NuGet. (Common, UWP, Xaml and Xaml.Controls)
I'm using the ValidatingTextBox, but I can't get rid of the following warning:

Could not load file or assembly 'WinUX.Common, Version=2.0.16271.3, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The bound assembly has a version that is lower than that of the request. (Exception from HRESULT: 0x80132000)

Greetings,
Steven

**Comment by jamesmcroft** [comment]
I'll investigate this issue and get back to you ASAP

**Comment by jamesmcroft** [comment]
@jsrijkee could you provide some more information about this issue. As a quick test, I created a blank UWP app and added all the packages from NuGet, added the ValidatingTextBox to the MainPage and it appears to be working okay.

**Comment by jsrijkee** [comment]
Hi James,

 

I must have done something wrong, because everything is working now properly.

Thank you for your reply.

 

Groeten,

Steven Rijkee

 

* 0621517003   

* steven@rijkee.nl

 

Van: James Croft [mailto:notifications@github.com] 
Verzonden: dinsdag 18 oktober 2016 12:42
Aan: jamesmcroft/WinUX-UWP-Toolkit <WinUX-UWP-Toolkit@noreply.github.com>
CC: jsrijkee <steven@rijkee.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [jamesmcroft/WinUX-UWP-Toolkit] Can't get rid of warnings (#14)

 

@jsrijkee <https://github.com/jsrijkee>  could you provide some more information about this issue. As a quick test, I created a blank UWP app and added all the packages from NuGet, added the ValidatingTextBox to the MainPage and it appears to be working okay.
