### ISSUE TITLE
Expander

### ISSUE THREAD

**Issue by imZEH** [jamesmcroft/WinUX-UWP-Toolkit#15]
![capture](https://cloud.githubusercontent.com/assets/7591030/19504528/902ebd40-95ed-11e6-9bc8-5737d9fa484e.PNG)

is their a chance to remove the incircled element on the image and make a background on header ?.

**Comment by jamesmcroft** [comment]
This would require a change to the way the functionality works. That arrow is the checkbox that opens and closes the expander

**Comment by imZEH** [comment]
how about  changing the color  ?  Would that be possible ?

Thanks

**Comment by jamesmcroft** [comment]
I'm currently looking into a change in this control which should allow you to change the icon, or even remove it entirely. I'll keep you posted.

**Comment by imZEH** [comment]
Pretty Awesome. Hoping to customize the header text as well, like having padding ,margin,fon, etc. :) 

Thanks

**Comment by jamesmcroft** [comment]
Hey, I'll be releasing an updated version of this control soon which is currently in the develop branch. You can customize the control like this in your XAML:

    <controls:Expander UseAnimations="True" HeaderGlyphVisibility="Visible" Margin="20">
        <controls:Expander.Header>
            <TextBlock Text="Header text" Margin="10" VerticalAlignment="Center" />
        </controls:Expander.Header>
        <controls:Expander.HeaderGlyph>
            <Viewbox Width="12">
                <Grid>
                    
                </Grid>
            </Viewbox>
        </controls:Expander.HeaderGlyph>

        <Grid>
            <TextBlock Text="This is the content." Foreground="Black" Margin="10" />
        </Grid>
    </controls:Expander>

I'll be pushing out a release soon with these changes! :smile:

**Comment by jamesmcroft** [comment]
These changes are now [available on NuGet ](https://www.nuget.org/packages?q=WinUX) as version 2.3.16349.2.

**Comment by imZEH** [comment]
awesome. Your the best . Thank you so much.
