### ISSUE TITLE
range slider wiki link goes to readme

### ISSUE THREAD

**Issue by jj09** [jamesmcroft/WinUX-UWP-Toolkit#5]

**Comment by jamesmcroft** [comment]
Apologies, will add some detail around the RangeSlider ASAP.

**Comment by jamesmcroft** [comment]
I've updated the wiki page with an example of how it can be used. You can also find a working example in the WinUX sample application.

[RangeSlider - wiki page](https://github.com/jamesmcroft/WinUX-UWP-Toolkit/wiki/RangeSlider-control)
