### ISSUE TITLE
Range Slider does not update when setting *SelectedValue in code

### ISSUE THREAD

**Issue by weretygr** [jamesmcroft/WinUX-UWP-Toolkit#7]
When setting either of these properties, the visual display does not update. The value does stick and can be retrieved but there is no visual indication of the change.

**Comment by jamesmcroft** [comment]
I'll take a look at this as soon as possible. Thanks for the find!

**Comment by jamesmcroft** [comment]
Fixed as part of PR #9.

Restructured the code for the RangeSlider control.
